// Copies ABIs (and bytecode for deployment) from forge's out/ into the keeper and the web app.
//   forge build && node script/export-abi.mjs
import { readFileSync, writeFileSync } from "node:fs";

const read = (file, name) => JSON.parse(readFileSync(new URL(`../out/${file}/${name}.json`, import.meta.url)));
const contracts = {
  MockUSDC: ["MockUSDC.sol", "usdcAbi"],
  IdentityRegistry: ["IdentityRegistry.sol", "registryAbi"],
  MidenShareToken: ["MidenShareToken.sol", "tokenAbi"],
  NavOracle: ["NavOracle.sol", "oracleAbi"],
  LiquidityManager: ["LiquidityManager.sol", "liquidityAbi"],
  StrategyManager: ["StrategyManager.sol", "strategyAbi"],
  SimulatedHyperliquidAdapter: ["SimulatedHyperliquidAdapter.sol", "adapterAbi"],
  MidenVault: ["MidenVault.sol", "vaultAbi"],
  EligibilityCompliance: ["EligibilityCompliance.sol", "complianceAbi"],
  TestnetOnboarding: ["TestnetOnboarding.sol", "onboardingAbi"],
  FundTimelock: ["FundTimelock.sol", "timelockAbi"],
};

const artifacts = {};
let ts = "// generated by contracts/script/export-abi.mjs — do not edit\n";
for (const [name, [file, exportName]] of Object.entries(contracts)) {
  const j = read(file, name);
  artifacts[name] = { abi: j.abi, bytecode: j.bytecode.object };
  ts += `export const ${exportName} = ${JSON.stringify(j.abi)} as const;\n`;
}
writeFileSync(new URL("../../keeper/src/artifacts.json", import.meta.url), JSON.stringify(artifacts));
writeFileSync(new URL("../../keeper/src/abi.ts", import.meta.url), ts);
writeFileSync(new URL("../../web/src/abi.ts", import.meta.url), ts);
console.log(`exported ${Object.keys(contracts).length} contracts`);
